In [12]:
a = [[1,2,3],[3,4,5],[5,6,7]]
b = [[1,2,3],[3,4,5],[5,6,7]]
c = [[0,0,0],[0,0,0],[0,0,0]]

for i in range (len(a)):
   for j in range (len(a[0])):
    c[i][j] = a[i][j] + b[i][j]

for row in c:
 print(row)

[2, 4, 6]
[6, 8, 10]
[10, 12, 14]


In [14]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])
result = a+b
print(result)

[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]
